### ISSUE TITLE
fatal error C1083: Cannot open include file: 'std_msgs/msg/string.hpp': No such file or directory 

### ISSUE THREAD

**Issue by yasinovgu** [dottantgal/ROS2_learning#3]
Hello Antonio, 

I am new in robotics and learning ROS2. I got your git link and downloaded the files.
I was trying to build "https://github.com/dottantgal/ROS2_learning/tree/main/CPP" using ros2_foxy environment. Unfortunately, "parameters" package was ended up with the error. Could you you please help to solve the issue?

**Comment by dottantgal** [comment]
Thanks for the report, I'll look into it asap
Thank you

**Comment by yasinovgu** [comment]
I tried to run this command to specifically build these two packages-- (Note that I am running ros2_foxy on windows)
"colcon build --packages-select custom_msg_and_srv service_server_and_client"

but the build failed again and the error is: 
**fatal error C1083: Cannot open include file: 'boost/algorithm/string.hpp': No such file or directory**

**Comment by yasinovgu** [comment]
Hello Antonio, 

**"Cannot open include file: 'std_msgs/msg/string.hpp': No such file or directory"**
This above problem is solved by adding **"std_msgs"** in cmake and package.xml file. 

However I do not know how to add **"boost/algorithm/string.hpp"** for the problem below: 
**"Cannot open include file: 'boost/algorithm/string.hpp': No such file or directory"**

**Comment by dottantgal** [comment]
So, I looked into it and on a fresh Ubuntu 20.04 + ROS Foxy installation I dont get any colcon build error, so I can't reproduce it

**Comment by CatInTheRain** [comment]
I solve the problem, @yasinovgu is right, but according to the Official Documentation you have also to specify the dependencies of the package `std_msgs` on each `ament_target_dependencies` inside the CMakeList.txt, like the following:
```cmake
ament_target_dependencies(parameters rclcpp std_msgs)
```
I'm on Ubuntu 22.04 ROS2 Humble and i face a strange problem with the build of action_tutorial so for now i ignored that package

**Comment by yasinovgu** [comment]
how to add **"boost/algorithm/string.hpp"** for the problem below:
Problem statement:  **"Cannot open include file: 'boost/algorithm/string.hpp': No such file or directory"**

@CatInTheRain  have you faced this above issue as well? If so, could you share your idea?

**Comment by CatInTheRain** [comment]
I am sorry @yasinovgu I don't face your problem. I am using docker inside Linux, i suggest you to try with the Humble distro, you can use WSL2. @dottantgal has created a new branch that works for me!
